/**
 * Web Push sender (RFC 8291 + VAPID RFC 8292).
 *
 * A dependency-free implementation using node:crypto. It generates the VAPID
 * JWT, encrypts the payload with the "aes128gcm" content-encoding that modern
 * browsers require, and POSTs to the subscription endpoint.
 *
 * Previously the app stored push subscriptions but never delivered a message:
 * there was no `web-push` dependency, and the FCM calls in fcm-batcher /
 * alert-dispatch-optimizer had no configured server key.
 *
 * Required environment variables:
 *   VAPID_PRIVATE_KEY  – PEM or base64url-unprefixed ECDSA P-256 private key
 *   VAPID_PUBLIC_KEY   – base64url-unprefixed ECDSA P-256 public key
 *   VAPID_SUBJECT      – mailto: or https: URL identifying the sender
 *
 * If any are missing, `sendWebPush` returns a no-op result so callers can run
 * without crashing in environments that haven't configured push.
 */

import crypto from 'node:crypto'

export interface PushSubscription {
  endpoint: string
  expirationTime?: number | null
  keys: {
    p256dh: string
    auth: string
  }
}

export interface PushPayload {
  title: string
  body: string
  data?: Record<string, unknown>
  tag?: string
  requireInteraction?: boolean
}

export interface SendResult {
  ok: boolean
  status: number
  endpoint: string
  /** When 404/410 the subscription is stale and should be removed. */
  subscriptionExpired?: boolean
  error?: string
}

function base64UrlDecode(input: string): Buffer {
  const b64 = input.replace(/-/g, '+').replace(/_/g, '/')
  const padded = b64 + '='.repeat((4 - (b64.length % 4)) % 4)
  return Buffer.from(padded, 'base64')
}

function getConfig() {
  const privateKey = process.env.VAPID_PRIVATE_KEY
  const publicKey = process.env.VAPID_PUBLIC_KEY
  const subject = process.env.VAPID_SUBJECT || 'mailto:noreply@openrelief.org'
  return { privateKey, publicKey, subject }
}

export function isWebPushConfigured(): boolean {
  const { privateKey, publicKey } = getConfig()
  return Boolean(privateKey && publicKey)
}

/**
 * Build the VAPID JWT (ES256) signed with the private key. The `aud` claim is
 * the subscription endpoint's origin.
 */
function buildVapidAuth(endpoint: string): {
  authorization: string
  cryptoKey: string
} {
  const { privateKey, publicKey, subject } = getConfig()
  if (!privateKey || !publicKey) {
    throw new Error('VAPID keys not configured')
  }

  const origin = new URL(endpoint).origin
  const header = Buffer.from(JSON.stringify({ typ: 'JWT', alg: 'ES256' })).toString('base64url')
  const now = Math.floor(Date.now() / 1000)
  const payload = Buffer.from(
    JSON.stringify({
      aud: origin,
      exp: now + 12 * 60 * 60,
      sub: subject
    })
  ).toString('base64url')

  // Load the ECDSA P-256 private key. Accept PEM directly or an unprefixed
  // base64url DER scalar (the format generated by web-push key utils).
  let keyObject: crypto.KeyObject
  try {
    keyObject = privateKey.includes('-----BEGIN')
      ? crypto.createPrivateKey({ key: privateKey, format: 'pem' })
      : crypto.createPrivateKey({
          key: derFromScalar(base64UrlDecode(privateKey)),
          format: 'der',
          type: 'pkcs8'
        })
  } catch {
    // Fallback: treat as raw base64url-encoded PKCS8
    keyObject = crypto.createPrivateKey({
      key: base64UrlDecode(privateKey),
      format: 'der',
      type: 'pkcs8'
    })
  }

  const signingInput = `${header}.${payload}`
  const signature = crypto.sign(null, Buffer.from(signingInput), keyObject)
  const jwt = `${signingInput}.${signature.toString('base64url')}`

  return {
    authorization: `vapid t=${jwt}, k=${publicKey}`,
    cryptoKey: `p256ecdsa=${publicKey}`
  }
}

/**
 * Convert an ECDSA P-256 private scalar into a PKCS8 DER buffer that
 * node:crypto can load. RFC8292 uses the uncompressed public key separately;
 * the private key here is the 32-byte scalar.
 */
function derFromScalar(scalar: Buffer): Buffer {
  if (scalar.length === 32) {
    // Wrap the raw scalar in a PKCS8 structure for prime256v1.
    const asn1 = crypto.createPrivateKey({ key: scalar, format: 'jwk', type: 'pkcs8' })
    return asn1.export({ type: 'pkcs8', format: 'der' }) as Buffer
  }
  // Already a DER blob.
  return scalar
}

/**
 * Encrypt `payload` for a subscription using aes128gcm (RFC 8188/8291).
 */
function encryptPayload(
  payload: Buffer,
  subscription: PushSubscription
): Buffer {
  const userPublicKey = base64UrlDecode(subscription.keys.p256dh)
  const userAuth = base64UrlDecode(subscription.keys.auth)

  // ECDH key pair (server / ephemeral)
  const ecdh = crypto.createECDH('prime256v1')
  ecdh.generateKeys()
  const serverPublicKey = ecdh.getPublicKey()
  const sharedSecret = ecdh.computeSecret(userPublicKey)

  // HKDF for content encryption key + nonce (RFC 8291)
  const keyInfo = Buffer.from('WebPush: info\u0000')
  const authSecret = Buffer.concat([userPublicKey, serverPublicKey])
  const cekInfo = Buffer.concat([keyInfo, authSecret, Buffer.from([0])])

  const contentEncryptionKey = hkdf(sharedSecret, userAuth, cekInfo, 16)
  const nonce = hkdf(contentEncryptionKey, userAuth, Buffer.from('Content-Encoding: nonce\u0000'), 12)

  const cipher = crypto.createCipheriv('id-aes128-GCM', contentEncryptionKey, nonce) as crypto.CipherGCM
  const ciphertext = Buffer.concat([cipher.update(payload), cipher.final(), cipher.getAuthTag()])

  // aes128gcm header: salt(16) + recordsize(4) + keyidlen(1) + keyid(65)
  const salt = crypto.randomBytes(16)
  const recordSize = Buffer.alloc(4)
  recordSize.writeUInt32BE(4096, 0)
  const keyIdLen = Buffer.from([serverPublicKey.length])

  return Buffer.concat([salt, recordSize, keyIdLen, serverPublicKey, ciphertext])
}

function hkdf(ikm: Buffer, salt: Buffer, info: Buffer, length: number): Buffer {
  const prk = crypto.createHmac('sha256', salt).update(ikm).digest()
  // HKDF-Expand (single block is enough for <= 32 bytes; we need 12 or 16)
  const t = crypto.createHmac('sha256', prk).update(Buffer.concat([info, Buffer.from([1])])).digest()
  return t.subarray(0, length)
}

/**
 * Send a Web Push notification to a single subscription.
 * Never throws on failure — returns a SendResult so callers can batch results.
 */
export async function sendWebPush(
  subscription: PushSubscription,
  message: PushPayload
): Promise<SendResult> {
  if (!isWebPushConfigured()) {
    return {
      ok: false,
      status: 0,
      endpoint: subscription.endpoint,
      error: 'Web Push not configured (missing VAPID keys)'
    }
  }

  try {
    const { authorization, cryptoKey } = buildVapidAuth(subscription.endpoint)
    const payload = encryptPayload(
      Buffer.from(JSON.stringify(message)),
      subscription
    )

    const response = await fetch(subscription.endpoint, {
      method: 'POST',
      headers: {
        Authorization: authorization,
        'Crypto-Key': cryptoKey,
        'Content-Encoding': 'aes128gcm',
        'Content-Type': 'application/octet-stream',
        TTL: '2419200'
      },
      body: payload
    })

    const expired = response.status === 404 || response.status === 410
    return {
      ok: response.ok,
      status: response.status,
      endpoint: subscription.endpoint,
      subscriptionExpired: expired,
      error: response.ok ? undefined : `Push endpoint returned ${response.status}`
    }
  } catch (error) {
    return {
      ok: false,
      status: 0,
      endpoint: subscription.endpoint,
      error: error instanceof Error ? error.message : 'Unknown push error'
    }
  }
}

/**
 * Broadcast a notification to many subscriptions. Stale subscriptions
 * (404/410) are returned so the caller can prune them from storage.
 */
export async function broadcastWebPush(
  subscriptions: PushSubscription[],
  message: PushPayload
): Promise<{ sent: number; failed: number; expired: PushSubscription[] }> {
  const results = await Promise.all(subscriptions.map(s => sendWebPush(s, message)))
  const expired = results
    .filter(r => r.subscriptionExpired)
    .map(r => subscriptions.find(s => s.endpoint === r.endpoint)!)
    .filter(Boolean)

  return {
    sent: results.filter(r => r.ok).length,
    failed: results.filter(r => !r.ok).length,
    expired
  }
}
